### ISSUE TITLE
Decoding predictions to strings

### ISSUE THREAD

**Issue by Andrew-Brown1** [sooftware/conformer#25]
Hi, thanks for the great repo. 

the README Usage example gives outputs as a torch tensor of ints. How would you suggest decoding these to strings (the actual speech)? 

Thanks!

**Comment by sooftware** [comment]
There should be a vocab file. like following:  
  
```python
examples = {
    0: "<pad>",
    1: "<sos>",
    2: "<eos>",
    3: "a",
    4: "b",
    ...
    ...
}
```

You can train with Conformer model [this repo](https://github.com/sooftware/lightning-asr)

**Comment by sooftware** [comment]
Sooner or later, a library will be unveiled to train multiple models, including the conformer transducer. I intend to release it as early as this week. I'll leave a comment here after I reveal it.

**Comment by sooftware** [comment]
www.github.com/sooftware/openspeech
