### ISSUE TITLE
Example of how to train conformer

### ISSUE THREAD

**Issue by CSLujunyu** [sooftware/conformer#26]
Hello, thanks for sharing this nice project. Could you provide some example on how to train conformer model with rnnt loss?

**Comment by sooftware** [comment]
Sooner or later, a library will be unveiled to train multiple models, including the conformer transducer. I intend to release it as early as this week. I'll leave a comment here after I reveal it.

**Comment by mjurkus** [comment]
Will this solve this issue I had here https://github.com/sooftware/KoSpeech/issues/119 ?

**Comment by sooftware** [comment]
@mjurkus I think you should -1 at `target_lengths` like `target_lengths -= 1`

**Comment by sooftware** [comment]
I'm now implementing the code with pytorch lightning, practically completing it and fixing it while looking for bugs. I think it would be a good reference for you.

**Comment by mjurkus** [comment]
Amazing! I also used Pytorch Lightning. Everything worked except that part. I'll look into your suggestion regarding `target_lengths`

**Comment by sooftware** [comment]
@mjurkus @CSLujunyu I release new library [openspeech](https://github.com/sooftware/openspeech). This repo contains conformed training.
