### ISSUE TITLE
The to.(self.device) in return

### ISSUE THREAD

**Issue by Skywatcher314** [sooftware/conformer#27]
The inputs.to(self.device) in ConformerConvmodule and FeedForwardModule will cause the network graph in tensorboard to fork and appear kind of messy. Is there any special reason to write like that? Since in most cases we should have send both the model and tensor to the device before we input the tensor to the model, probably no more sending action is needed?

**Comment by adobles96** [comment]
In addition to that it also breaks things when running on a computer w/o gpu. Even if you do `model.cpu()` that doesn't change the `device` attribute for the module & submodules, so when you hit a `inputs.to(self.device)` it tries to convert to cuda (the default value for `device`) and crashes.

**Comment by sooftware** [comment]
resolved #28
