### ISSUE TITLE
Doubts in Inference and Training

### ISSUE THREAD

**Issue by codemaster-22** [sooftware/conformer#29]
Hey why are we not maintaining something like blank token during Inference for each time step , and during training also won't there be some alignment problems ?

**Comment by sooftware** [comment]
Sorry for late response. I handle blank token when converts ids to tokens. like [this](https://github.com/openspeech-team/openspeech/blob/58ba00ff674f35b0d657fbf26f0bfb0070846a7b/openspeech/tokenizers/ksponspeech/character.py#L92).
